### ISSUE TITLE
Newsletter 

### ISSUE THREAD

**Issue by bluefin18** [NewEconomyMovement/ournem-homepage#1]
link at the top still "WIP"
Old issues 1,2,3,4 missing.
Need to include subscription link like the old one where people can key in their emails to subscribe to new issues.

**Comment by crackerhead** [comment]
link at the top still "WIP"
Sorry, I dont understand what you mean by that.

Old issues 1,2,3,4 missing.
Are you referring to the newsletter? I plan to work on an archive system, I will try to run it by the devs this weekend

Need to include subscription link like the old one where people can key in their emails to subscribe to new issues.
Good idea, I will look into that this wekeend as well.

**Comment by crackerhead** [comment]
Newsletter page has been added, issue closed
