### ISSUE TITLE
How to tell if you have 64 bit Chrome FAQ

### ISSUE THREAD

**Issue by jabo38** [NewEconomyMovement/ournem-homepage#2]
In Chrome, type chrome://chrome in your search bar, you will see the version #, and at the end of the line you will see bit #. either 32-bit or 64-bit.

if you have 64 bit it will say

but if you have 32 bit, it says nothing

http://www.howtogeek.com/199307/how-to-tell-if-you-have-the-32-bit-or-64-bit-version-of-google-chrome/

**Comment by crackerhead** [comment]
fixed, but for now the faq section will be removed until the community has updated it further.
